version: 2.1
description: Voiceflow's common CI/CD orb
executors:
  # Used to run tests
  code-test-executor:
    working_directory: ~/voiceflow # directory where steps will run
    resource_class: large
    environment:
      NODE_OPTIONS: --max-old-space-size=4096
    docker: # run the steps with Docker
      - image: circleci/node:12 # Test steps container
      - image: postgres:10.6-alpine # PostgresDB service container
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust # This is needed to ensure that the PG instance can be accessed locally without explicitly creating credentials
      - image: circleci/dynamodb:13-oracle # DynamoDB service container
      - image: circleci/redis:4.0-alpine # Redis service container
      - image: circleci/mongo:4.2.7 # MongoDB service container

  # Used to run container builds
  build-executor:
    working_directory: /tmp/vf-build
    docker:
      - image: voiceflow/ci-image:v3
    resource_class: medium

  # Used to run node-intensive tests and builds
  node-executor:
    working_directory: ~/voiceflow 
    docker: 
      - image: circleci/node:12 
    environment:
      NODE_OPTIONS: --max-old-space-size=4096
    resource_class: medium+

  default-executor: # used to run the release
    docker:
      - image: circleci/node:12
    resource_class: small

#--------------------------------------------------------------------------------------------------------------------

commands:
  install_aws_cli:
    steps:
      - run:
          name: Install pip3
          command: sudo apt update && sudo apt install -y python3-pip
      - run:
          name: Install AWS CLI
          command: pip3 install awscli

  setup_pg:
    steps:
      - run:
          name: Install psql for seeding db
          command: |
            sudo apt update
            sudo apt install -y postgresql-client
      - run:
          name: Wait for Postgres & Dynamo Docker Images
          command: dockerize -wait tcp://localhost:5432 -timeout 1m 

  setup_dynamodb:
    steps:
      - run:
          name: AWS Config
          command: ./scripts/mock_aws_credentials.sh
      - run:
          name: Wait for Dynamo Docker Image
          command: dockerize -wait tcp://localhost:8000 -timeout 1m

  setup_mongodb:
    steps:
      - run:
          name: Wait for MongoDB Docker Image
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

  lint_source:
    steps:
      - run:
          name: Lint source
          command: yarn lint:quiet

  lint_dockerfile:
    steps:
      - run:
          name: Lint dockerfiles
          command: |
            sudo wget -O /usr/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-Linux-x86_64
            sudo chmod +x /usr/bin/hadolint
            yarn lint:dockerfiles

  install_node_modules:
    parameters: 
      install_args: 
        description: Additional yarn install command options
        type: string
        default: ""
    steps:
      - restore_cache:
          keys:
            - node-module-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install packages
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            yarn install --frozen-lockfile << parameters.install_args >>
      - save_cache: # special step to save the dependency cache
          key: node-module-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  build_push_image: 
    parameters: 
      image_repo: 
        description: The container image repository
        type: string
      release_pkg: 
        description: The npm package name to be released
        type: string
    steps:
      - checkout # special step to check out source code to working directory
      - setup_remote_docker
      - run:
          name: "Build docker image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_REPO="<< parameters.image_repo >>"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            # Fix semantic versioning 
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              npm config set unsafe-perm true # needed for npx to work
              set +e  # Don't exit on the any error (for semantic-release)
              npx semantic-release@15 --prepare --dry-run | tee sem_release.output  # print semver to screen and force return 0
              SEM_VER=$(cat sem_release.output | grep 'Published release ' | awk '{print $NF}')  # Get release semver
              set -e  # Don't exit on the any error (for semantic-release)
              if [ -z "$SEM_VER" ]; then
                echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
                SEM_VER=$(npm view << parameters.release_pkg >> version)
              fi
            else
              SEM_VER=$CIRCLE_BRANCH-$CIRCLE_SHA1
            fi
            echo -e "Building with SEM_VER=$SEM_VER"
            $(aws ecr get-login --no-include-email --region us-east-1)
            docker build \
              --build-arg NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} \
              --build-arg build_BUILD_NUM=${CIRCLE_BUILD_NUM} \
              --build-arg build_BUILD_URL=${CIRCLE_BUILD_URL}	\
              --build-arg build_GIT_SHA=${CIRCLE_SHA1} \
              --build-arg build_SEM_VER=${SEM_VER} \
              -t $IMAGE_NAME .
      - run:
          name: "Push docker images"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_REPO="<< parameters.image_repo >>"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            docker push $IMAGE_NAME
            BRANCH_NAME=$CIRCLE_BRANCH
            if [[ -z "$CIRCLE_BRANCH" && ! -z "$CIRCLE_TAG" ]]; then
              BRANCH_NAME="master"
            fi
            docker tag $IMAGE_NAME $IMAGE_REPO:latest-$BRANCH_NAME
            docker push $IMAGE_REPO:latest-$BRANCH_NAME

  deploy_image: 
    description: Deploy an image into a K8s cluster
    parameters: 
      image_repo: 
        description: The container image repository
        type: string
      target: 
        description: The target deployment/daemonset/statefulset prefix to modify
        type: string
        default: deployment/some-repo
      namespace:
        description: The namespace the target resides in 
        type: string
      tagged: 
        description: Running on a git tag?
        type: boolean
        default: false
    steps:
      - run:
          name: Update kubernetes image
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_REPO="<< parameters.image_repo >>"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            if [[ "<< parameters.tagged >>" != "false" ]]; then
              aws eks --region us-east-1 update-kubeconfig --name development
              kubectl set image --namespace << parameters.namespace >> << parameters.target >>-master app=$IMAGE_NAME
              aws eks --region us-east-1 update-kubeconfig --name production
              kubectl set image --namespace << parameters.namespace >> << parameters.target >>-production app=$IMAGE_NAME
            else
              aws eks --region us-east-1 update-kubeconfig --name development
              kubectl set image --namespace << parameters.namespace >> << parameters.target >>-$CIRCLE_BRANCH app=$IMAGE_NAME
              if [ "$CIRCLE_BRANCH" == "master" ]; then
                aws eks --region us-east-1 update-kubeconfig --name production
                kubectl set image --namespace << parameters.namespace >> << parameters.target >>-production app=$IMAGE_NAME
              fi
            fi

  build_deploy_dev_env:
    description: Deploy an image into a K8s cluster
    parameters: 
      image_repo: 
        description: The container image repository
        type: string
      ssh_key: 
        description: The SSH key with write permissions to the repository
        type: string
      component: 
        description: The component type for development environment deployment
        type: string
    steps:
      - checkout # special step to check out source code to working directory
      - setup_remote_docker # Need this to run DinD
      - attach_workspace:
          at: /tmp/vf-build
      - add_ssh_keys: # To enable write access to repository for removing development environment branches
          fingerprints:
            - << parameters.ssh_key >>
      - run:
          name: "Build dev environment image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_REPO="<< parameters.image_repo >>"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            SEM_VER="$CIRCLE_BRANCH-$CIRCLE_SHA1"
            $(aws ecr get-login --no-include-email --region us-east-1)
            set +e
            DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $IMAGE_NAME > /dev/null 2>&1
            SEARCH_IMAGE_RESULT=$?
            set -e
            if [[ $SEARCH_IMAGE_RESULT -ne 0 ]]; then   # Only build the image if there are no existing images 
              docker build \
                --build-arg NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} \
                --build-arg build_BUILD_NUM=${CIRCLE_BUILD_NUM} \
                --build-arg build_BUILD_URL=${CIRCLE_BUILD_URL}	\
                --build-arg build_GIT_SHA=${CIRCLE_SHA1} \
                --build-arg build_SEM_VER=${SEM_VER} \
                -t $IMAGE_NAME . 
              docker push $IMAGE_NAME
            fi
            git push origin --delete $CIRCLE_BRANCH --no-verify # Clean up git branch
      - run:
          name: Install latest envcli utility
          command: |
            API_URL="https://$GITHUB_TOKEN:@api.github.com/repos/voiceflow/envcli"
            ASSET_ID=$(curl $API_URL/releases/latest | jq -r '.assets[2].id')
            curl -J -L -H "Accept: application/octet-stream" "$API_URL/releases/assets/$ASSET_ID" --output envcli.tar.gz
            tar -xf envcli.tar.gz
      - run:
          name: "Deploy dev environment image"
          command: |
            IMAGE_TAG="k8s-$CIRCLE_SHA1"
            IMAGE_REPO="<< parameters.image_repo >>"
            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
            ENV_NAME="${CIRCLE_BRANCH%%_*}"
            aws eks --region us-east-1 update-kubeconfig --name development
            NON_INTERACTIVE=true ./envcli edit component << parameters.component >> << parameters.component >> -n $ENV_NAME -i $IMAGE_NAME

#--------------------------------------------------------------------------------------------------------------------

jobs: 
  release:
    executor: default-executor
    parameters: 
      install_args: 
        description: Additional yarn install command options
        type: string
        default: ""
    steps:
      - checkout
      - install_node_modules:
          install_args: "<< parameters.install_args >>"
      - run: npx semantic-release@15
