executor: build-executor
parameters:
  namespace:
    description: The namespace to look at
    type: string
  tagged:
    description: if tagged
    type: boolean
    default: false
  component:
    description: The component name that has changed
    type: string
  package:
    description: The monorepo package that has been changed
    type: string
    default: ""
  success_slack_notify:
    description: Post to Slack on successful deployment?
    type: boolean
    default: true
  force_execute:
    description: "force to notify, if there is a change or not."
    type: boolean
    default: false
steps:
  - post_image_push_actions:
      namespace: "<< parameters.namespace >>"
      tagged: "<< parameters.tagged >>"
      success_slack_notify: "<< parameters.success_slack_notify >>"
      component: "<< parameters.component >>"
      package: "<< parameters.package >>"
      force_execute: "<< parameters.force_execute >>"