executor: build-executor
parameters:
  working_directory:
    description: Directory containing chart directories
    type: string
    default: "./"
  prepublish_steps:
    description: Steps to run on repo before publishing charts
    type: steps
    default: []
steps:
  - checkout_clone
  - set-beta-version:
      working_directory: << parameters.working_directory >>
  - steps: << parameters.prepublish_steps >>
  - helm-add-repos
  - run:
      name: Package and publish prerelease charts to S3
      working_directory: << parameters.working_directory >>
      command: <<include(scripts/helm/publish-prerelease.sh)>>
  - run:
      name: Package and publish prerelease charts to ECR
      working_directory: << parameters.working_directory >>
      command: <<include(scripts/helm/publish-prerelease-ecr.sh)>>
