executor: build-executor
parameters:
  working_directory:
    description: Directory containing package.json
    type: string
    default: "./"
steps:
  - checkout
  - helm-add-repos
  - run:
      name: Package and publish charts
      working_directory: << parameters.working_directory >>
      command: <<include(scripts/helm/package-publish-charts.sh)>>
