executor: build-executor
parameters:
  working_directory:
    description: Directory containing chart directories
    type: string
    default: "./"
steps:
  - checkout
  - check_commit_message:
      commit_message: "[pre-release]"
  - helm-add-repos
  - helm-package-publish-prerelease:
      working_directory: "<< parameters.working_directory >>"
