executor: build-executor
parameters:
  working_directory:
    description: Directory containing chart directories
    type: string
    default: "./"
steps:
  - checkout
  - set-beta-version:
      working_directory: << parameters.working_directory >>
  - helm-add-repos
  - run:
      name: Package and publish charts
      working_directory: << parameters.working_directory >>
      command: <<include(scripts/helm/publish-prerelease.sh)>>
