executor: build-executor
parameters:
  chart_directory:
    description: Directory containining charts
    type: string
    default: .
  charts:
    description: List of charts to publish
    type: string
    default: ""
steps:
  - checkout
  - helm-add-repos
  - run:
      name: Package and publish charts
      working_directory: << parameters.chart_directory >>
      command: <<include(scripts/helm/package-publish-charts.sh)>>
      environment:
        CHARTS: << parameters.charts >>
