parameters:
  working_directory:
    description: Directory containing package.json
    type: string
    default: './'
  run_in_background:
    description: run the command in background
    type: boolean
    default: false
  step_name:
    description: Name of the step
    type: string
    default: Build
  extra_args:
    description: Additional yarn command options
    type: string
    default: ""
  wait:
    description: wait until all the commands are finished
    type: boolean
    default: false
  run_in_container:
    description: Run build in a container
    type: boolean
    default: false
  request_remote_docker:
    description: Request remote Docker
    type: boolean
    default: false
  container_folder_to_copy:
    description: Container folder to copy after the execution
    type: string
    default: ""
  container_image_to_build:
    description: Container image to run the build
    type: string
    default: "168387678261.dkr.ecr.us-east-1.amazonaws.com/ci-node-build-image:v1"
  package:
    description: Container folder to copy after the execution
    type: string
    default: ""
  package_folder:
    description: Package folder
    type: string
    default: "packages"
steps:
  - yarn_command:
      working_directory: << parameters.working_directory >>
      run_in_background: << parameters.run_in_background >>
      request_remote_docker: << parameters.request_remote_docker >>
      run_in_container: << parameters.run_in_container >>
      container_folder_to_copy: << parameters.container_folder_to_copy >>
      container_image: << parameters.container_image_to_build >>
      monorepo_package: << parameters.package >>
      monnorepo_package_folder: << parameters.package_folder >>
      step_name: << parameters.step_name >>
      wait: << parameters.wait >>
      yarn_command: yarn build<<# parameters.package >>:<</ parameters.package >><< parameters.package >> << parameters.extra_args >>
