steps:
  - run:
      name: ECR Docker Login
      command: |
        if aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 168387678261.dkr.ecr.us-east-1.amazonaws.com; then
            echo "Login succeeded with get-login-password"
        else
            echo "Login with get-login-password failed, falling back to get-login"
            $(aws ecr get-login --no-include-email --region us-east-1)
        fi
