description: >
  Install git and setup for treeless shallow clone before hadolint

parameters:
  ssh_fingerprint:
    description: SSH Key
    type: string

steps:
  - add_ssh_keys:
      fingerprints:
        - "<< parameters.ssh_fingerprint >>"

  - run:
      name: Install git
      command: "apt update && apt install -y git"

  - run:
      name: Setup SSH
      command: |
        mkdir -p ~/.ssh
        echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' >>~/.ssh/known_hosts

  - run:
      name: Treeless Shallow Checkout
      command: |
        git clone --single-branch --no-tags --filter=tree:0 --depth 1 -b "${CIRCLE_BRANCH}" "${CIRCLE_REPOSITORY_URL}" ~/project
