description: Deploy an image into a K8s cluster
parameters:
  namespace:
    description: The namespace the target resides in
    type: string
  tagged:
    description: Running on a git tag?
    type: boolean
    default: false
  success_slack_notify:
    description: Post to Slack on successful deployment?
    type: boolean
    default: true
  sentry:
    description: Report deployment to sentry
    type: boolean
    default: false
  ssh_key:
    description: The SSH key with write permissions to the repository
    type: string
    default: "4c:f6:5f:e5:7a:e9:b4:03:91:6a:93:e5:0e:60:c2:a6"
  component:
    description: The component name that has changed
    type: string
    default: ""
  package:
    description: The monorepo package that has been changed
    type: string
    default: ""
  package_folder:
    description: The monorepo package that has been changed
    type: string
    default: "packages"
  force_execute:
    description: '[DEPRECATED] no effect, kept for backward compatibility'
    type: boolean
    default: false
steps:
  - checkout_shallow_clone
  - add_ssh_keys: # To enable write access to repository
      fingerprints:
        - << parameters.ssh_key >>
  - when:
      condition: << parameters.tagged >>
      steps:
        - run:
            name: Post Image Push Actions
            environment:
              SENTRY: << parameters.sentry >>
              NAMESPACE: '<< parameters.namespace >>'
              COMPONENT: '<< parameters.component >>'
              PACKAGE: '<< parameters.package >>'
            command: <<include(scripts/docker/post_image_push.sh)>>
        - when:
            condition: <<parameters.success_slack_notify>>
            steps:
              - notify_slack:
                  channel: product_releases
                  event: pass
                  template: success_tagged_deploy_1
        - notify_slack:
            channel: product_releases
            event: fail
            mentions: "@engteam"
            template: basic_fail_1
