version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  validate-orb:
    jobs:
      - orb-tools/validate:
          orb-path: orb.yml

  publish-orb:
    jobs:
      - orb-tools/increment:
          orb-path: orb.yml
          orb-ref: voiceflow/common
          publish-token-variable: ${CIRCLE_TOKEN}
          segment: patch
          validate: true
          filters:
              branches:
                only: master