version: 2.1
orbs:
  orb-tools: circleci/orb-tools@11.2.0
  cli: circleci/circleci-cli@0.1.9

workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - pack
      - orb-tools/publish:
          context: dev-test
          requires: [pack]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          pub-type: dev


  publish-orb:
    when: << pipeline.git.tag >>
    jobs:
      - pack
      - orb-tools/publish:
          context: dev-test
          requires: [pack]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          pub-type: production


jobs:
  # Copies configs from their respective subdirectories into
  # the appropriate root directories before packing
  # Necessary because of https://github.com/CircleCI-Public/circleci-cli/issues/755
  pack:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: Copy configuration from subdirectories
          command: |
            for DIR in commands jobs executors examples; do
              # Copy all files in all subdirectories into orb-src
              find src/$DIR -type f -exec mv {} src/$DIR \; || :
            done;
      - run:
          name: Pack
          command: mkdir ./dist && circleci orb pack --skip-update-check src > ./dist/orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/
