version: 2.1
orbs:
  orb-tools: circleci/orb-tools@11.2.0

workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - collect-section-files
      - orb-tools/pack:
          requires: [collect-section-files]
      - orb-tools/publish:
          context: dev-test
          requires: [orb-tools/pack]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          pub-type: dev


  publish-orb:
    when: << pipeline.git.tag >>
    jobs:
      - collect-section-files
      - orb-tools/pack:
          requires: [collect-section-files]
      - orb-tools/publish:
          context: dev-test
          requires: [orb-tools/pack]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          pub-type: production


jobs:
  # Copies configs from their respective subdirectories into
  # the appropriate root directories
  # Necessary because of https://github.com/CircleCI-Public/circleci-cli/issues/755
  collect-section-files:
    docker:
      - image: busybox:latest
    steps:
      - checkout
      - run:
          name: Copy configuration from subdirectories
          command: |
            mkdir orb-src
            for DIR in commands jobs executors examples; do
              # Copy all files in all subdirectories into orb-src
              find src/$DIR -type f -exec mv {} orb-src/$DIR \; || :
            done;
      - persist_to_workspace:
          root: .
          paths:
            - orb-src
