version: 2.1
orbs:
  orb-tools: circleci/orb-tools@11.2.0
  cli: circleci/circleci-cli@0.1.8

prod_filter: &prod_filter
  tags:
    only: /.*/

dev_filter: &dev_filter
  branches:
    ignore: master

jobs:
  validate-orb:
    executor: cli/default
    steps:
      - checkout
      - cli/install
      - run:
          command: circleci orb validate orb.yml

workflows:
  publish-dev-orb:
    jobs:
      - validate-orb:
          filters: *dev_filter
      - orb-tools/publish:
          filters: *dev_filter
          requires: [validate-orb]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          orb-dir: '.'
          pub-type: dev


  publish-orb:
    jobs:
      - validate-orb:
          filters: *prod_filter
      - orb-tools/publish:
          filters: *prod_filter
          requires: [validate-orb]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          orb-dir: '.'
          pub-type: production