version: 2.1
orbs:
  orb-tools: circleci/orb-tools@11.2.0

workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - orb-tools/pack
      - orb-tools/publish:
          context: dev-test
          requires: [validate-orb]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          orb-dir: '.'
          pub-type: dev


  publish-orb:
    when: << pipeline.git.tag >>
    jobs:
      - orb-tools/pack
      - orb-tools/publish:
          context: dev-test
          requires: [validate-orb]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          orb-dir: '.'
          pub-type: production