version: 2.1
orbs:
  orb-tools: circleci/orb-tools@11.2.0


# Filter required due to CircleCI behaviour described here: https://discuss.circleci.com/t/cant-trigger-workflow-on-git-tag-push-using-when-condition/43252/5
tags_filter: &tags_filter
  filters:
    tags:
      only: ['/.*/']

# Copies configs from their respective subdirectories into
# the appropriate root directories before packing
# Necessary because of https://github.com/CircleCI-Public/circleci-cli/issues/755
run: &extract_sections_from_subdirectories
  name: Copy configuration from subdirectories
  command: |
    for DIR in commands jobs executors examples; do
      # Copy all files in all subdirectories into orb-src
      find src/$DIR -type f -exec mv {} src/$DIR \; || :
    done;


workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - orb-tools/pack:
          pre-steps:
            - <<: *extract_sections_from_subdirectories
      - orb-tools/publish:
          context: dev-test
          requires: [pack]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          pub-type: dev


  publish-orb:
    when: << pipeline.git.tag >>
    jobs:
      - orb-tools/pack:
          <<: *tags_filters
          pre-steps:
            - <<: *extract_sections_from_subdirectories
      - orb-tools/publish:
          context: dev-test
          requires: [pack]
          vcs-type: << pipeline.project.type >>
          orb-name: voiceflow/common
          pub-type: production
          <<: *tags_filters
