version: 2.1
orbs:
  orb-tools: circleci/orb-tools@10.1.0
  cli: circleci/circleci-cli@0.1.8


jobs:
  validate-orb:
    executor: cli/default
    steps:
      - checkout
      - cli/install
      - run:
          command: circleci orb validate orb.yml

workflows:
  validate-orb:
    jobs:
      - validate-orb:
          filters:
            branches:
              ignore: master
      - orb-tools/publish-dev:
          orb-path: orb.yml
          orb-name: voiceflow/common
          publish-token-variable: CIRCLE_TOKEN
          filters:
            branches:
              ignore: master

  publish-orb:
    jobs:
      - validate-orb
      - orb-tools/increment:
          orb-path: orb.yml
          orb-ref: voiceflow/common
          publish-token-variable: CIRCLE_TOKEN
          segment: patch
          validate: true
          filters:
              branches:
                only: master