description: Package and publish helm charts
parameters:
    working_directory:
        description: Directory containing package.json
        type: string
        default: "./"
steps:
    - run:
          name: Package and publish charts
          working_directory: << parameters.working_directory >>
          command: <<include(scripts/helm/package-and-publish.sh)>>
