description: Package and publish prerelease of helm charts
parameters:
    working_directory:
        description: Directory containing chart directories
        type: string
        default: "./"
steps:
    - run:
        name: Package and publish charts
        working_directory: << parameters.working_directory >>
        command: <<include(scripts/helm/publish-prerelease.sh)>>