description: Package and publish helm charts
parameters:
    working_directory:
        description: Directory containing package.json
        type: string
        default: "./"
steps:
    - run:
          name: Package and publish charts
          working_directory: << parameters.working_directory >>
          command: |
            for file in */ ; do
                if [[ -d "$file" && -f "$file/$file/Chart.yaml" ]]; then
                echo "packaging $file";
                cd $file;
                helm dep update $file;
                helm package $file;
                pattern="*.tgz";
                chart=( $pattern );
                channel=$(cat $file/Chart.yaml | yq -r '.annotations."release-channel"')
                echo "publishing in $channel channel";
                if [[ $channel == "private" ]]; then
                    helm s3 push --force ${chart[0]} voiceflow-charts-s3-private;
                fi
                if [[ $channel == "public" ]]; then
                    helm s3 push --force ${chart[0]} voiceflow-charts-s3;
                fi
                if [[ $channel == "beta" ]]; then
                    helm s3 push --force ${chart[0]} voiceflow-charts-s3-beta;
                fi
                cd ..;
                fi;
            done
