parameters:
  executor:
    type: executor
executor: << parameters.executor >>
working_directory: /home/circleci/code
steps:
  - setup_remote_docker
  - std_checkout
  - std_clone_repo:
      repo_name: openapi-schemas
      directory: schemas
      branch: master
  - std_restore_cache:
      cache_name: node
      use_lockfile: true
  - std_restore_cache:
      cache_name: build
  - run:
      name: Restore OpenAPI Schemas
      working_directory: /home/circleci/schemas
      command: |
        cp -v --parents apps/*/openapi.json /home/circleci/code
  - run:
      name: Test OpenAPI Schema
      command: |
        yarn ci:schema:validate
